# Generated by Django 4.2.11 on 2024-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.IntegerField()),
                ('projects_count', models.IntegerField()),
                ('support_hours', models.IntegerField()),
                ('workers_count', models.IntegerField()),
            ],
        ),
    ]
